// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import OfferTimeFormatController from "./offer_time_format_controller"
application.register("offer-time-format", OfferTimeFormatController)
